"""empty message

Revision ID: 28024ae7f4da
Revises: a21af042cdaf
Create Date: 2018-11-30 16:21:18.384761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28024ae7f4da'
down_revision = 'a21af042cdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_documents', sa.Column('document_path', sa.Text(), nullable=True))
    op.add_column('candidate_documents', sa.Column('grammar_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_documents', 'grammar_score')
    op.drop_column('candidate_documents', 'document_path')
    # ### end Alembic commands ###
