"""empty message

Revision ID: 88d69b547cd7
Revises: 8ff298e88039
Create Date: 2018-10-11 18:57:00.363935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88d69b547cd7'
down_revision = '8ff298e88039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('keyword_type', sa.String(length=80), nullable=True),
    sa.Column('keyword_tags_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(length=80), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywords')
    # ### end Alembic commands ###
