"""empty message

Revision ID: a21af042cdaf
Revises: 4d23ec638040
Create Date: 2018-10-11 22:34:58.071883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21af042cdaf'
down_revision = '4d23ec638040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_rules',
    sa.Column('grammar_rule_id', sa.String(100), nullable=False),
    sa.Column('grammar_rules_category', sa.String(length=80), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('grammar_rule_id')
    )
    op.create_table('candidate_document_lines',
    sa.Column('candidate_document_lines_id', sa.Integer(), nullable=False),
    sa.Column('candidate_document_id', sa.Integer(), nullable=False),
    sa.Column('document_line_text', sa.Text(), nullable=True),
    sa.Column('grammar_issue', sa.Boolean(), nullable=True),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_document_id'], ['candidate_documents.candidate_document_id'], ),
    sa.PrimaryKeyConstraint('candidate_document_lines_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_document_lines')
    op.drop_table('grammar_rules')
    # ### end Alembic commands ###
