"""empty message

Revision ID: bda58b894e66
Revises: 59f44da236ad
Create Date: 2018-10-11 18:18:02.979070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda58b894e66'
down_revision = '59f44da236ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('skill', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(length=80), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('notice_period', sa.String(length=80), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('location_current', sa.Text(), nullable=True),
    sa.Column('location_prefferred', sa.Text(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.Column('wfh', sa.Boolean(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('company_website', sa.Text(), nullable=True),
    sa.Column('date_added', sa.Integer(), nullable=True),
    sa.Column('date_added_year', sa.Integer(), nullable=True),
    sa.Column('date_added_month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
